services:
  postgresdb:
    image: postgres:alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: humanslovedbs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - internal-network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U app"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  backend:
    # build: ./backend
    # env_file:
    #   - ./backend/.env
    environment:
      POSTGRES_SERVER: postgresdb
      POSTGRES_PASSWORD: humanslovedbs
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgresdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 5173
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
