services:
  postgresdb:
    image: stevecmd/devops-stage-2-postgresdb:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: humanslovedbs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network

  backend:
    image: stevecmd/devops-stage-2-backend:latest
    environment:
      POSTGRES_SERVER: postgresdb
      POSTGRES_PASSWORD: humanslovedbs
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgresdb
    networks:
      - internal-network

  frontend:
    image: stevecmd/devops-stage-2-frontend:latest
    expose:
      - 5173
    ports:
      - "5173:5173"
    networks:
      - internal-network

  adminer:
    image: stevecmd/devops-stage-2-adminer:latest
    ports:
      - "8080:8080"
    networks:
      - internal-network

  nginx:
    image: stevecmd/devops-stage-2-nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - adminer
    networks:
      - internal-network

  proxy-manager:
    image: stevecmd/devops-stage-2-proxy-manager:latest
    ports:
      - "8090:8080"
      - "81:81"   # HTTP Port for Let's Encrypt Challenge
      - "444:444" # HTTPS Port for Let's Encrypt Challenge
    environment:
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_USER: app
      DB_PASSWORD: humanslovedbs
      DB_NAME: app
    volumes:
      - ./proxy-manager/data:/data
      - ./proxy-manager/letsencrypt:/etc/letsencrypt
      - ./proxy-manager/var/log:/var/log
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  postgres_data:
